### ISSUE TITLE
Old membrane keyboards

### ISSUE THREAD

**Issue by goyalyashpal** [Skycode22/HIDs#1]
Hi,

I was wondering why are there no open source membrane keyboards. They seem dead cheap to make, and i'd love to tinker with those. But i was not able to find any on the internet.

Do you any insights on why that might be the case?

coming via 
* https://www.reddit.com/r/olkb/comments/vh6yrm/openex_an_open_source_kensington_expert_inspired/
* https://www.reddit.com/r/olkb/comments/7j4nma/wirelesswired_split_orthogonal_keyboard_concept/

**Comment by Skycode22** [comment]
not sure exactly why that is the case other than the unique method of production for the membranes, IE I have no idea where to even start with making those membranes, lol. honestly it seems like a great opportunity to design one yourself and make it open source!!
